[package]
name = "netool"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.7", features = ["derive"] }
cmd_lib = "1.9.4"
colored = "2.1.0"
prettytable-rs = "0.10.0"
serde = "1.0.203"
serde_derive = "1.0.203"
serde_json = "1.0.117"
